services:
  emo-face-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: emo-face-prod
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-pro}
    env_file:
      - .env
    restart: unless-stopped
    command: ["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "4", "app:app"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: emo-face-network
