services:
  emo-face-app:
    build: .
    image: emo-face-app # 添加固定的鏡像名稱
    container_name: emo-face-web
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-False}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-pro}
    env_file:
      - .env
    volumes:
      # 開發時掛載代碼目錄，便於即時修改
      - .:/app
      - /app/.venv # 確保使用鏡像中的 .venv
      # 但排除不需要的目錄
      # - /app/__pycache__
      # - /app/.git
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: emo-face-network
